[project]
name = "LORE_sa"
version = "0.0.1"
requires-python = ">=3.6"
[build-system]
requires = ["setuptools",
    "wheel",
    "numpy~=1.21.6",
    "pandas~=1.3.5"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
